import { createHash, randomBytes } from "node:crypto";
import { mkdir, readdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import { DeleteObjectsCommand, GetObjectCommand, ListObjectsV2Command, S3Client, PutObjectCommand } from "@aws-sdk/client-s3";

// Review image storage.
//  - originals: byte-identical copy in PRIVATE storage (never served publicly; GPS EXIF stays private)
//  - thumb/large: re-encoded WebP (EXIF stripped) in the derivatives store, namespaced per merchant internally:
//      s/<shop_id>/r/<review_id>/<public_id>-320.webp | -1600.webp
//  - public URL: <MEDIA_PUBLIC_URL>/<public_id>-320.webp — ONLY the opaque asset id, never a shop/review/product id.
//    The /media route resolves it (tenant.server publicMediaKey) and serves it only while the photo is public.
// Driver "local" (dev) writes to MEDIA_LOCAL_DIR/{private,public}; "s3" works with any S3-compatible store.

export const ALLOWED_TYPES: Record<string, string> = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
};

export function sniffType(buf: Buffer): string | null {
  if (buf.length > 3 && buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff) return "image/jpeg";
  if (buf.length > 8 && buf.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) return "image/png";
  if (buf.length > 12 && buf.toString("ascii", 0, 4) === "RIFF" && buf.toString("ascii", 8, 12) === "WEBP") return "image/webp";
  return null;
}

export const sha256 = (buf: Buffer) => createHash("sha256").update(buf).digest("hex");

type Visibility = "private" | "public";

let s3: S3Client | null = null;
function s3Client() {
  s3 ??= new S3Client({
    endpoint: process.env.S3_ENDPOINT || undefined,
    region: process.env.S3_REGION || "auto",
    credentials: {
      accessKeyId: process.env.S3_ACCESS_KEY_ID || "",
      secretAccessKey: process.env.S3_SECRET_ACCESS_KEY || "",
    },
  });
  return s3;
}

async function put(visibility: Visibility, key: string, body: Buffer, contentType: string) {
  if ((process.env.MEDIA_DRIVER || "local") === "s3") {
    const Bucket = visibility === "public" ? process.env.S3_BUCKET_PUBLIC : process.env.S3_BUCKET_PRIVATE;
    await s3Client().send(
      new PutObjectCommand({
        Bucket,
        Key: key,
        Body: body,
        ContentType: contentType,
        CacheControl: "private, no-store", // nothing is served straight from storage; the /media route decides
      }),
    );
    return;
  }
  const file = path.join(localDir(), visibility, key);
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, body);
}

/** Private, per-shop storage for merchant import files (never served by any route). */
export const importFileKey = (shopId: string, jobId: string, name: "source.csv" | "images.zip") => `${shopPrefix(shopId)}/imports/${jobId}/${name}`;
export const storePrivateFile = (key: string, body: Buffer, contentType: string) => put("private", key, body, contentType);

/** Reads a private object by its internal key (keys are generated by Proofly, never taken from user input). */
export async function readPrivate(key: string): Promise<Buffer | null> {
  if ((process.env.MEDIA_DRIVER || "local") === "s3") {
    const out = await s3Client().send(new GetObjectCommand({ Bucket: process.env.S3_BUCKET_PRIVATE, Key: key })).catch(() => null);
    const bytes = await out?.Body?.transformToByteArray();
    return bytes ? Buffer.from(bytes) : null;
  }
  return readFile(path.join(localDir(), "private", key)).catch(() => null);
}

type Vis = "private" | "public";
const bucket = (v: Vis) => (v === "public" ? process.env.S3_BUCKET_PUBLIC : process.env.S3_BUCKET_PRIVATE);

/** Lists stored objects under a prefix (keys are Proofly-generated, e.g. "s/<shop>/"), with their last-modified time. */
export async function listObjects(v: Vis, prefix: string): Promise<{ key: string; modified: Date }[]> {
  if ((process.env.MEDIA_DRIVER || "local") === "s3") {
    const out: { key: string; modified: Date }[] = [];
    let token: string | undefined;
    do {
      const r = await s3Client().send(new ListObjectsV2Command({ Bucket: bucket(v), Prefix: prefix, ContinuationToken: token }));
      for (const o of r.Contents ?? []) if (o.Key) out.push({ key: o.Key, modified: o.LastModified ?? new Date(0) });
      token = r.IsTruncated ? r.NextContinuationToken : undefined;
    } while (token);
    return out;
  }
  const root = path.join(localDir(), v);
  const out: { key: string; modified: Date }[] = [];
  const walk = async (dir: string) => {
    for (const e of await readdir(dir, { withFileTypes: true }).catch(() => [])) {
      const full = path.join(dir, e.name);
      if (e.isDirectory()) await walk(full);
      else out.push({ key: path.relative(root, full).split(path.sep).join("/"), modified: (await stat(full)).mtime });
    }
  };
  await walk(path.join(root, prefix));
  return out;
}

/** Deletes stored objects by key (idempotent). */
export async function deleteObjects(v: Vis, keys: string[]) {
  if (!keys.length) return 0;
  if ((process.env.MEDIA_DRIVER || "local") === "s3") {
    for (let i = 0; i < keys.length; i += 1000) {
      await s3Client().send(new DeleteObjectsCommand({ Bucket: bucket(v), Delete: { Objects: keys.slice(i, i + 1000).map((Key) => ({ Key })), Quiet: true } }));
    }
    return keys.length;
  }
  const root = path.join(localDir(), v);
  for (const k of keys) {
    const full = path.resolve(root, k);
    if (full.startsWith(root + path.sep)) await rm(full, { force: true });
  }
  return keys.length;
}

/** Everything stored for a shop (both stores), for shop/redact. */
export async function deleteShopObjects(shopId: string) {
  let n = 0;
  for (const v of ["private", "public"] as const) n += await deleteObjects(v, (await listObjects(v, `${shopPrefix(shopId)}/`)).map((o) => o.key));
  if ((process.env.MEDIA_DRIVER || "local") !== "s3") for (const v of ["private", "public"]) await rm(path.join(localDir(), v, shopPrefix(shopId)), { recursive: true, force: true });
  return n;
}

export function localDir() {
  return path.resolve(process.env.MEDIA_LOCAL_DIR || "./storage");
}

export type MediaSize = 320 | 1600;
/** Opaque public asset id: 128 random bits, hex. Unrelated to any database or Shopify identifier. */
export const newPublicId = () => randomBytes(16).toString("hex");

/** The public URL of one derivative. The only identifier in it is the opaque asset id. */
export function mediaUrl(publicId: string, size: MediaSize) {
  return `${(process.env.MEDIA_PUBLIC_URL || "").replace(/\/$/, "")}/${publicId}-${size}.webp`;
}

/** Parses a public media file name ("<32 hex>-320.webp"); anything else (paths, internal keys, originals) → null. */
export function parsePublicMediaName(name: string): { publicId: string; size: MediaSize } | null {
  const m = /^([0-9a-f]{32})-(320|1600)\.webp$/.exec(name);
  return m ? { publicId: m[1], size: Number(m[2]) as MediaSize } : null;
}

/** Reads one stored derivative by its internal key (never called with user input — keys come from the resolver). */
export async function readDerivative(key: string): Promise<Buffer | null> {
  if ((process.env.MEDIA_DRIVER || "local") === "s3") {
    const out = await s3Client().send(new GetObjectCommand({ Bucket: process.env.S3_BUCKET_PUBLIC, Key: key })).catch(() => null);
    const bytes = await out?.Body?.transformToByteArray();
    return bytes ? Buffer.from(bytes) : null;
  }
  return readFile(path.join(localDir(), "public", key)).catch(() => null);
}

export interface StoredImage {
  publicId: string;
  publicBytes: number;
  storageKey: string;
  thumbKey: string;
  largeKey: string;
  contentType: string;
  fileSize: number;
  sha256: string;
  width: number | null;
  height: number | null;
}

/** Per-shop key prefix: every object belongs to exactly one tenant (listing/deletion per shop, no collisions). */
export const shopPrefix = (shopId: string) => `s/${shopId}`;

/** Stores one review image (private original + two WebP derivatives) under a fresh opaque public id. */
export async function storeReviewImage(shopId: string, reviewId: string, original: Buffer): Promise<StoredImage> {
  const contentType = sniffType(original);
  if (!contentType) throw new Error("Unsupported image type");
  const hash = sha256(original);
  const storageKey = `${shopPrefix(shopId)}/originals/${reviewId}/${hash}.${ALLOWED_TYPES[contentType]}`;
  const publicId = newPublicId();
  const base = `${shopPrefix(shopId)}/r/${reviewId}/${publicId}`;

  const img = sharp(original, { failOn: "error" }).rotate(); // apply EXIF orientation, then metadata is dropped
  const meta = await img.metadata();
  const [thumb, large] = await Promise.all([
    img.clone().resize({ width: 320, height: 320, fit: "cover" }).webp({ quality: 76 }).toBuffer(),
    img.clone().resize({ width: 1600, height: 1600, fit: "inside", withoutEnlargement: true }).webp({ quality: 82 }).toBuffer(),
  ]);

  await put("private", storageKey, original, contentType);
  await put("public", `${base}-320.webp`, thumb, "image/webp");
  await put("public", `${base}-1600.webp`, large, "image/webp");

  // EXIF orientations 5–8 swap width/height.
  const swap = (meta.orientation ?? 1) >= 5;
  return {
    publicId,
    publicBytes: thumb.length + large.length,
    storageKey,
    thumbKey: `${base}-320.webp`,
    largeKey: `${base}-1600.webp`,
    contentType,
    fileSize: original.length,
    sha256: hash,
    width: (swap ? meta.height : meta.width) ?? null,
    height: (swap ? meta.width : meta.height) ?? null,
  };
}
