import { mkdir, readdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { DeleteObjectsCommand, GetObjectCommand, ListObjectsV2Command, S3Client, PutObjectCommand } from "@aws-sdk/client-s3";

// Private, per-shop file storage. The only files Proofly stores are merchants' import CSVs, which no route ever serves.
// Driver "local" (dev) writes to MEDIA_LOCAL_DIR/private; "s3" uses any S3-compatible private bucket.
const isS3 = () => (process.env.MEDIA_DRIVER || "local") === "s3";

let s3: S3Client | null = null;
function s3Client() {
  s3 ??= new S3Client({
    endpoint: process.env.S3_ENDPOINT || undefined,
    region: process.env.S3_REGION || "auto",
    credentials: { accessKeyId: process.env.S3_ACCESS_KEY_ID || "", secretAccessKey: process.env.S3_SECRET_ACCESS_KEY || "" },
  });
  return s3;
}

export function localDir() {
  return path.resolve(process.env.MEDIA_LOCAL_DIR || "./storage");
}
const root = () => path.join(localDir(), "private");

/** Per-shop key prefix: every object belongs to exactly one tenant (listing/deletion per shop, no collisions). */
export const shopPrefix = (shopId: string) => `s/${shopId}`;
export const importFileKey = (shopId: string, jobId: string) => `${shopPrefix(shopId)}/imports/${jobId}/source.csv`;

export async function storePrivateFile(key: string, body: Buffer, contentType: string) {
  if (isS3()) {
    await s3Client().send(new PutObjectCommand({ Bucket: process.env.S3_BUCKET_PRIVATE, Key: key, Body: body, ContentType: contentType, CacheControl: "private, no-store" }));
    return;
  }
  const file = path.join(root(), key);
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, body);
}

/** Reads a private object by its internal key (keys are generated by Proofly, never taken from user input). */
export async function readPrivate(key: string): Promise<Buffer | null> {
  if (isS3()) {
    const out = await s3Client().send(new GetObjectCommand({ Bucket: process.env.S3_BUCKET_PRIVATE, Key: key })).catch(() => null);
    const bytes = await out?.Body?.transformToByteArray();
    return bytes ? Buffer.from(bytes) : null;
  }
  return readFile(path.join(root(), key)).catch(() => null);
}

/** Lists stored objects under a prefix (keys are Proofly-generated, e.g. "s/<shop>/"), with their last-modified time. */
export async function listObjects(prefix: string): Promise<{ key: string; modified: Date }[]> {
  const out: { key: string; modified: Date }[] = [];
  if (isS3()) {
    let token: string | undefined;
    do {
      const r = await s3Client().send(new ListObjectsV2Command({ Bucket: process.env.S3_BUCKET_PRIVATE, Prefix: prefix, ContinuationToken: token }));
      for (const o of r.Contents ?? []) if (o.Key) out.push({ key: o.Key, modified: o.LastModified ?? new Date(0) });
      token = r.IsTruncated ? r.NextContinuationToken : undefined;
    } while (token);
    return out;
  }
  const walk = async (dir: string) => {
    for (const e of await readdir(dir, { withFileTypes: true }).catch(() => [])) {
      const full = path.join(dir, e.name);
      if (e.isDirectory()) await walk(full);
      else out.push({ key: path.relative(root(), full).split(path.sep).join("/"), modified: (await stat(full)).mtime });
    }
  };
  await walk(path.join(root(), prefix));
  return out;
}

/** Deletes stored objects by key (idempotent). */
export async function deleteObjects(keys: string[]) {
  if (!keys.length) return 0;
  if (isS3()) {
    for (let i = 0; i < keys.length; i += 1000) {
      await s3Client().send(new DeleteObjectsCommand({ Bucket: process.env.S3_BUCKET_PRIVATE, Delete: { Objects: keys.slice(i, i + 1000).map((Key) => ({ Key })), Quiet: true } }));
    }
    return keys.length;
  }
  for (const k of keys) {
    const full = path.resolve(root(), k);
    if (full.startsWith(root() + path.sep)) await rm(full, { force: true });
  }
  return keys.length;
}

/** Everything stored for a shop, for shop/redact. */
export async function deleteShopObjects(shopId: string) {
  const n = await deleteObjects((await listObjects(`${shopPrefix(shopId)}/`)).map((o) => o.key));
  if (!isS3()) await rm(path.join(root(), shopPrefix(shopId)), { recursive: true, force: true });
  return n;
}
